#include "jokes.h"

char* jokes[JOKE_SIZE] = {
    "I told my wife she should embrace her mistakes. She gave me a hug.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "I'm reading a book on anti-gravity. It's impossible to put down.",
    "I asked the librarian if the library had books on paranoia. She whispered, 'They're right behind you...'",
    "Why was the math book sad? It had too many problems.",
    "I'm thinking of reasons to go to Switzerland. The flag is a big plus.",
    "I used to play piano by ear, but now I use my hands.",
    "Parallel lines have so much in common. It’s a shame they’ll never meet.",
    "Why couldn't the bicycle stand up by itself? It was two-tired.",
    "What do you call fake spaghetti? An impasta.",
    "I told my computer I needed a break, and now it won’t stop sending me holiday offers.",
    "Why do we tell actors to 'break a leg'? Because every play has a cast.",
    "What’s orange and sounds like a parrot? A carrot.",
    "Why don't scientists trust atoms? Because they make up everything.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "I'm no cheetah... You're lion!",
    "Why was the belt arrested? For holding up a pair of pants.",
    "How do you organize a space party? You planet.",
    "I'd tell you a chemistry joke but I know I wouldn't get a reaction.",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "Why was six scared of seven? Because seven eight (ate) nine.",
    "I have a joke about time travel, but you didn't like it.",
    "What's a ghost's favorite dessert? I scream.",
    "What do you call a factory that makes okay products? A satisfactory.",
    "I would tell you a joke about an elevator, but it’s an uplifting experience.",
    "Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "I've got a great joke about construction, but I'm still working on it.",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus.",
    "Why couldn't the leopard play hide and seek? Because he was always spotted.",
    "What do you call a pile of cats? A meowtain.",
    "Did you hear about the kidnapping at the park? They woke up.",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "What do you call an alligator in a vest? An investigator.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "What's brown and sticky? A stick.",
    "What do you call a boomerang that won't come back? A stick.",
    "What did the fish say when he hit the wall? Dam.",
    "I'd tell a WiFi joke, but I'm pretty sure you wouldn't get the connection.",
    "What’s the best thing about Switzerland? I don’t know, but the flag is a big plus.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why don't some couples go to the gym? Because some relationships don't work out.",
    "I’m reading a book on the history of glue. I just can’t seem to put it down.",
    "Why do bees hum? Because they don’t know the words.",
    "What did the left eye say to the right eye? Between us, something smells.",
    "Why don't we ever tell secrets on a farm? Because the corn has ears.",
    "I ordered a chicken and an egg from Amazon. I’ll let you know.",
    "What's the best way to watch a fly fishing tournament? Live stream."
};
